### PR TITLE
Feature shape support 

### PR DESCRIPTION
**Pull request by gfl94**
+ Add a shapefile parser outside kernel
+ Add shape support for DataFrame API and SQL query, all tests passed

TODO: 

+ Serialization part needs to be optimized

### CODE REVIEW

**Comment by Skyprophet** [comment]
What do you mean by `serialization part needs to be optimized`?

**Comment by gfl94** [comment]
@Skyprophet In the file [KryoShapeSerializer.java](https://github.com/gfl94/Simba/blob/597d24b50441c09715d2fe780b69ad21f9c513f3/engine/sql/catalyst/src/main/java/org/apache/spark/sql/catalyst/expressions/KryoShapeSerializer.java), I replace all the kryo serialization part with a `ByteArray` stream, because I have some difficulty in finding **ALL** the necessary classes(like classes from `JTS` library) for kryo registration. This can be optimized if we can register all the classes needed to be registered.

**Comment by Skyprophet** [comment]
@gfl94 Will this cause any bugs in the program? Or it is just an optimization issue that influence performance?

**Comment by gfl94** [comment]
@Skyprophet Just an optimization issue. But if we leave the serializer what it is now, we need to rename the serializer, because we do not really use Kryo serializer at all.

**Comment by Skyprophet** [comment]
@gfl94 Please do not use `nio`, which is the original java serializer, for it's bad performance and high space consumption. Do use kyro to serialize shape to byte array.

**Comment by Skyprophet** [comment]
@gfl94 Please fix the file path problem as I mentioned in the meeting. Then, I will merge this PR to develop.

**Comment by Skyprophet** [comment]
Why you close this PR. If you finish updating, just leave a comment, and then I can merge....

**Comment by gfl94** [comment]
@Skyprophet I'm not so familiar with the PR system on GITHUB, sorry for that:)  

Finish modification.

**Pull request merged**
