### PR TITLE
Fix sqlContext bug while loading index from disk.

### PR DESCRIPTION
**Pull request by gfl94**
Fix the `SQLContext` bug mentioned in [Issue#6](https://github.com/InitialDLab/Simba/issues/6).

### CODE REVIEW

**Comment by Skyprophet** [comment]
You should not save and load the whole `sqlContext` since it contains much more information than just configurations. What I meant is to just save "useful" information for further use.

Specifically, you just load back local index and global index. And try to fit it into current sqlContext!

**Comment by Skyprophet** [comment]
@gfl94 BTW, please checkout from the current develop again, and open a new PR. Or I cannot do automatic merging.

**Comment by gfl94** [comment]
@Skyprophet I think you misunderstand me, I do not modify the current `SQLContext`, I use the current `SQLContext` parameters to load the partition info.

We need to add an alternative path for `SQLContext` because if we use the `CreateIndex` method and `LoadIndex` method. I think we need a `SQLContext` to construct a `RTreeIndexedRelation` but we do not have one. So I add one in this PR.

**Comment by Skyprophet** [comment]
@gfl94 You should have a constructor to handle loaded index, rather than simple use to original one to rebuild this. By using this, I don't think you need all information in the sqlContext.

**Comment by gfl94** [comment]
@Skyprophet You mean that I should pass the parameters like [`numShufflePartitions`, etc](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/index/IndexedRelation.scala#L185-L188) with a struct or a tuple?

I need the four parameters from the current SQLContext, and I know that it's  inappropriate to construct a LogicalPlan node with SQLContext, but I wonder how to implement it.

If I use `child.sqlContext` while loading index,  I will get a NullPointerException, the error message is given below(the line number might be a little different, it refers to `child.sqlContext`):

```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.spark.sql.index.RTreeIndexedRelation.<init>(IndexedRelation.scala:192)
	at org.apache.spark.sql.IndexManager.loadIndex(IndexManager.scala:130)
	at org.apache.spark.sql.SQLContext.loadIndex(SQLContext.scala:392)
	at org.apache.spark.examples.sql.IndexExample$.main(IndexExample.scala:69)
	at org.apache.spark.examples.sql.IndexExample.main(IndexExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by Skyprophet** [comment]
I mean you need a totally different constructor for loaded index. Currently, we only have one constructor for `IndexRelation`, which is used for building index from scratch.

By defining a new constructor, I don't think you need anything other than persisted RDD and some meta data.

**Pull request closed without merging**
